#!/bin/sh

test -f /home/weaves/etc/q.rc && . /home/weaves/etc/q.rc
test -f $HOME/.q.rc && . $HOME/.q.rc

. /home/weaves/etc/use-q

: ${HOSTNAME:=$(uname -n)}
HOSTNAME=${HOSTNAME%%.*}

prog=$(basename $0)

prefix=@prefix@
exec_prefix=@exec_prefix@
exec_prefix_set=no

d_usage () {
cat <<EOF
usage: qsys-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version]

In addition:
 --pkgdatadir
 --sysconfdir
 --qhomedir
 --qprogdir
 --qtrdrhost
 --qtrdrport
 --qprog
 --QTRDR

EOF
}

if test $# -eq 0; then
    echo "${usage}" 1>&2
    exit 1
fi

while test $# -gt 0; do
case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
esac

case $1 in
    --prefix=*)
    prefix=$optarg
    if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
    fi
    ;;
    --prefix)
    echo $prefix
    ;;
    --exec-prefix=*)
    exec_prefix=$optarg
    exec_prefix_set=yes
    ;;
    --exec-prefix)
    echo $exec_prefix
    ;;
    --version)
    echo @PACKAGE_VERSION@
    ;;
    --pkgdatadir)
    echo /home/weaves/share/qsys
    ;;
    --sysconfdir)
    echo /home/weaves/etc
    ;;
    --qhomedir)
    echo /home/weaves/src/q
    ;;
    --qprogdir)
    echo /home/weaves/src/q/l32
    ;;
    --qtrdrhost)
    echo reine
    ;;
    --qtrdrport)
    echo 15001
    ;;
    --qprog)
    echo /home/weaves/src/q/l32/q
    ;;
    --QTRDR)
    echo $QTRDR
    ;;
    *)
    d_usage 2>&1
    exit 1
    ;;
esac
shift
done

